### PR TITLE
B4

### PR DESCRIPTION
**Pull request by smuckati1**
All updates to SLX File made

### CODE REVIEW

**Review by sameer-kariappa — CHANGES_REQUESTED** [review]
Are you sure about the way the flooring works to say we do not need it?

**Comment by smuckati1** [comment]
I reviewed the setup at this link - this updates DO make sense. I say we e make it.
Let me know if you want to hold a design review instead.

**Comment by sameer-kariappa** [comment]
Alright I guess we're good - will review merge conflicts and then approve if all is good

**Review by sameer-kariappa — APPROVED** [review]

**Comment by sameer-kariappa** [comment]
Changes Appreoved _  will delete the branch
Please feel free to do the same on your version of MATLAB as well

**Pull request merged**
