### PR TITLE
B gain

### PR DESCRIPTION
**Pull request by smuckati1**
Gain optimized for use

### CODE REVIEW

**Review by sameer-kariappa — COMMENTED** [review]
Are you sure this is the way to go? Check with Kelle on if this dataset makes her work easy?

**Comment by smuckati1** [comment]
Checked with Kelle - she wanted the values to be a bit lower, and I updated  the same

**Comment by sameer-kariappa** [comment]
Changes look good. Check for latest commits to the master and make sure you integrate them in!

**Comment by sameer-kariappa** [comment]
Great! Just make sure you merge in any uopadtes already made to the mainiline.
The Updates are approved!

**Review by sameer-kariappa — DISMISSED** [review]
Updates made sense. I approve this update.

**Review by sameer-kariappa — APPROVED** [review]

**Pull request merged**
