### PR TITLE
Gain control data

### PR DESCRIPTION
**Pull request by smuckati1**
Updates the Gains to take values from the Workspace  it makes it easier to tune these and test them!

### CODE REVIEW

**Comment by sameer-kariappa** [comment]
I like the changes. The Y limits are still not corrected, but I guess that was already assigned to someone else. will work Fine once the branches are merged.

**Comment by smuckati1** [comment]
I tired the changes, and yeah they work well together. 
With all updates made, I will now hold the Degsign REvoew

**Comment by smuckati1** [comment]
Updates complete based on Design Review - the branch is ready for Merge!

**Comment by sameer-kariappa** [comment]
Merge complete and sucessful!

**Pull request merged**
